Repository team-joytas/wooco-fe, pull requests merged in 2025-06, with the labels that each got.

#300 [기능] 클라이언트 피드백 수집을 위한 Sentry 연결
  app/global-error.tsx
  instrumentation-client.ts
  instrumentation.ts
  next.config.js
  package-lock.json
  package.json
  sentry.edge.config.ts
  sentry.server.config.ts
  tsconfig.json
Labels: feature, dependencies

#303 [HOTFIX] 기본 프로필 이미지 깨짐 문제 해결
  src/features/place-review/image-view.tsx
  src/views/detail-course/index.tsx
Labels: fix

#309 [리팩토링] 코스 목록 페이지 URL 수정
  app/courses/by-region/page.tsx
  app/courses/page.tsx
  app/layout.tsx
  src/views/list-course/index.tsx
  src/views/list-course/main-course.tsx
  src/views/list-course/region-course.tsx
  src/widgets/header/main-header.tsx
Labels: refactor
