Repository team-joytas/wooco-fe, pull requests merged in 2025-01, with the labels that each got.

#56 [기능] 로그인 로직 추가
  app/login/components/Login.tsx
  app/login/page.tsx
  app/oauth/kakao/callback/page.tsx
  next.config.js
  src/entities/login/api.ts
  src/shared/axios/index.ts
  src/views/login/index.tsx
Labels: feature

#61 [기능] 유저 정보 수정 기능 추가
  app/oauth/kakao/callback/page.tsx
  app/plans/page.tsx
  app/users/[id]/page.tsx
  next.config.js
  package-lock.json
  package.json
  src/entities/login/api.ts
  src/entities/user/api.ts
  src/entities/user/type.ts
  src/features/user/upload-profile-image.tsx
  src/shared/api/index.ts
  src/shared/axios/index.ts
  src/shared/utils/imageUtil.ts
  src/views/detail-user/index.tsx
  src/views/update-user/index.tsx
  src/widgets/header/index.tsx
Labels: refactor, feature

#63 [수정] 헤더 수정 및 메인 페이지 수정
  app/layout.tsx
  src/views/main/index.tsx
  src/widgets/course-plan-layout/index.tsx
  src/widgets/default-header/index.tsx
  src/widgets/header/index.tsx
Labels: fix, feature

#65 [기능] 코스 api 연결 및 기타 api 연결 및 수정
  app/courses/[id]/comments/page.tsx
  app/courses/[id]/page.tsx
  app/courses/page.tsx
  app/plans/[id]/update/page.tsx
  app/plans/components/CourseCard.tsx
  app/plans/page.tsx
  app/users/[id]/page.tsx
  src/entities/comment/api.ts
  src/entities/comment/query.ts
  src/entities/comment/type.ts
  src/entities/course/api.ts
  src/entities/course/type.ts
  src/entities/place/type.ts
  src/entities/user/type.ts
  src/features/comment/card-comment.tsx
  src/features/course/card-course.tsx
  src/features/course/card-grid-course.tsx
  src/features/course/card-list-course.tsx
  src/features/course/list-user-course.tsx
  src/features/main/section-new-course.tsx
  src/features/place/drag-place-item.tsx
  src/features/user/upload-profile-image.tsx
  src/shared/entities/api.ts
  src/shared/entities/type.ts
  src/shared/ui/KakaoMap.tsx
  src/shared/ui/PlaceCollapse.tsx
  src/shared/ui/ProfileImage.tsx
  src/shared/utils/date.ts
  src/views/add-course/index.tsx
  src/views/detail-comment/index.tsx
  src/views/detail-course/index.tsx
  src/views/detail-user/index.tsx
  src/views/list-course/index.tsx
  src/views/search-course/index.tsx
  src/views/search-place/index.tsx
  src/views/update-plan/index.tsx
  src/widgets/add-course-plan/index.tsx
  src/widgets/course-plan-layout/index.tsx
  src/widgets/default-header/index.tsx
  src/widgets/header/index.tsx
Labels: refactor, feature

#66 [기능] 코스 생성, 삭제 api 연결 및 기타 오류 수정
  app/courses/add-region/page.tsx
  src/entities/category/type.ts
  src/entities/comment/api.ts
  src/entities/course/api.ts
  src/entities/course/type.ts
  src/entities/place/api.ts
  src/entities/place/type.ts
  src/features/course/card-course.tsx
  src/features/course/card-list-course.tsx
  src/features/course/form-course.tsx
  src/features/place/drag-place-item.tsx
  src/shared/entities/type.ts
  src/shared/ui/ImageWithIndex.tsx
  src/shared/ui/KakaoMap.tsx
  src/shared/ui/PlaceCollapse.tsx
  src/shared/ui/RegionCascader.tsx
  src/shared/ui/SelectCategories.tsx
  src/shared/utils/date.ts
  src/views/add-course/index.tsx
  src/views/add-region/index.tsx
  src/views/detail-comment/index.tsx
  src/views/detail-course/index.tsx
  src/views/list-course/index.tsx
  src/views/search-course/index.tsx
  src/views/search-place/index.tsx
  src/views/update-plan/index.tsx
  src/widgets/add-course-plan/index.tsx
  src/widgets/course-plan-layout/index.tsx
  src/widgets/drag-place/index.tsx
  src/widgets/header/index.tsx
  src/widgets/list-course/index.tsx
Labels: fix, refactor, feature

#67 [기능] 유저 관련 api 연결 및 로직 수정, 기타 수정
  app/not-found/page.tsx
  app/plans/page.tsx
  app/users/[id]/page.tsx
  app/users/setting/page.tsx
  package-lock.json
  package.json
  src/entities/course/api.ts
  src/entities/login/api.ts
  src/entities/user/api.ts
  src/features/course/card-course.tsx
  src/features/course/list-user-course.tsx
  src/features/plan/list-user-place.tsx
  src/shared/store/userStore.ts
  src/shared/ui/ImageWithIndex.tsx
  src/views/detail-user/index.tsx
  src/views/list-course/index.tsx
  src/views/update-user/index.tsx
  src/widgets/course-plan-layout/index.tsx
  src/widgets/default-footer/index.tsx
  src/widgets/default-header/index.tsx
  src/widgets/header/index.tsx
Labels: fix, refactor, feature

#68 [기능] 메인 화면 수정 및 공지사항 추가
  app/notices/1/page.tsx
  src/assets/images/notice.png
  src/entities/course/api.ts
  src/features/course/grid-course.tsx
  src/features/main/card-announcement.tsx
  src/features/main/section-announcement.tsx
  src/features/main/section-like-course.tsx
  src/features/main/section-new-course.tsx
  src/shared/ui/NoLikedCourse.tsx
  src/views/main/index.tsx
  src/widgets/default-footer/index.tsx
Labels: fix, feature

#70 [기능] react-query 도입 및 기타 수정
  app/courses/[id]/comments/page.tsx
  app/courses/[id]/modify/page.tsx
  app/courses/[id]/page.tsx
  app/layout.tsx
  app/not-found/page.tsx
  app/plans/page.tsx
  package.json
  src/entities/comment/query.ts
  src/entities/course/query.ts
  src/entities/login/api.ts
  src/entities/user/query.ts
  src/features/course/form-course.tsx
  src/features/main/section-like-course.tsx
  src/features/main/section-new-course.tsx
  src/features/place/drag-place-item.tsx
  src/shared/axios/index.ts
  src/shared/entities/query.ts
  src/views/detail-comment/index.tsx
  src/views/detail-course/index.tsx
  src/views/detail-user/index.tsx
  src/views/list-course/index.tsx
  src/views/search-course/index.tsx
  src/views/search-place/index.tsx
  src/views/update-course/index.tsx
  src/views/update-user/index.tsx
  src/widgets/add-course-plan/index.tsx
  src/widgets/default-footer/index.tsx
  src/widgets/drag-place/index.tsx
  src/widgets/header/index.tsx
  src/widgets/list-course/index.tsx
Labels: fix, refactor, feature

#78 [수정] UI 수정 및 로직 수정
  app/layout.tsx
  app/plans/[id]/update/page.tsx
  app/template.tsx
  app/users/[id]/page.tsx
  src/entities/course/api.ts
  src/entities/course/query.ts
  src/features/course/card-list-course.tsx
  src/features/main/section-announcement.tsx
  src/features/main/section-like-course.tsx
  src/features/place/drag-place-item.tsx
  src/features/plan/list-user-place.tsx
  src/features/user/user-profile-section.tsx
  src/features/user/user-tab-button.tsx
  src/views/detail-user/index.tsx
  src/views/search-course/index.tsx
  src/views/update-plan/index.tsx
  src/views/update-user/index.tsx
  src/widgets/course-plan-detail-layout/index.tsx
  src/widgets/course-plan-form-layout/index.tsx
Labels: fix, refactor, feature

#79 [수정] 빌드 오류 수정
  src/entities/course/api.ts
  src/entities/course/query.ts
Labels: fix

#80 [기능] 지역별 코스 목록 페이지 UI 수정 및 api 연결
  app/courses/by-region/page.tsx
  app/courses/page.tsx
  src/entities/course/api.ts
  src/entities/course/query.ts
  src/entities/user/api.ts
  src/entities/user/query.ts
  src/entities/user/type.ts
  src/features/course/form-course.tsx
  src/features/main/section-like-course.tsx
  src/shared/store/regionStore.ts
  src/shared/ui/RegionCascader.tsx
  src/views/list-course/index.tsx
  src/views/main-course/index.tsx
  src/widgets/header/index.tsx
  src/widgets/list-course/index.tsx
Labels: refactor, feature

#82 [기능] 토큰 reissue 로직 추가
  package-lock.json
  package.json
  src/shared/axios/index.ts
  src/shared/axios/signature.ts
  src/shared/ui/RegionCascader.tsx
  src/views/list-course/index.tsx
  src/widgets/default-footer/index.tsx
Labels: fix, feature

#84 [수정] 장소 order 적용
  src/shared/ui/PlaceCollapse.tsx
Labels: fix

#86 [수정] 코스/플랜 수정 페이지 오류 해결
  src/widgets/course-plan-form-layout/index.tsx
  src/widgets/header/index.tsx
Labels: fix

#87 [기능] 카테고리 설정 기능 추가
  src/entities/course/api.ts
  src/entities/course/query.ts
  src/shared/ui/SelectCategories.tsx
  src/views/list-course/index.tsx
Labels: feature

#88 [기능 및 수정] 플랜 삭제 api 연결 및 플랜-코스로 공유 기능 구현
  src/entities/plan/api.ts
  src/entities/plan/query.ts
  src/widgets/course-plan-detail-layout/index.tsx
  src/widgets/course-plan-form-layout/index.tsx
  src/widgets/header/index.tsx
Labels: fix, feature
