Repository team-joytas/wooco-fe, pull requests merged in 2025-07, with the labels that each got.

#314 [수정] 코스 수정 권한 확인 로직 추가
  src/views/detail-course/index.tsx
  src/widgets/course-plan-form-layout/index.tsx
Labels: fix

#315 [기능] 코스에 등록할 수 있는 장소 개수 5개로 제한
  src/widgets/course-plan-form-layout/index.tsx
Labels: feature

#319 [수정-콘솔 경고] 중복된 key 값에 대한 경고 해소
  src/shared/provider/AppProviders.tsx
Labels: fix

#320 [리팩토링] React Query 쿼리 키 및 refetch 로직 개선
  src/entities/comment/api/delete-comment.ts
  src/entities/comment/api/get-comments.ts
  src/entities/comment/api/post-comment.ts
  src/entities/comment/api/queryKey.ts
  src/entities/comment/api/update-comment.ts
  src/entities/course/api/delete-course-like.ts
  src/entities/course/api/delete-course.ts
  src/entities/course/api/get-course.ts
  src/entities/course/api/get-courses.ts
  src/entities/course/api/post-course-like.ts
  src/entities/course/api/post-course.ts
  src/entities/course/api/queryKey.ts
  src/entities/course/api/update-course.ts
  src/entities/place/api/delete-place-review.ts
  src/entities/place/api/get-place-review.ts
  src/entities/place/api/get-place-reviews.ts
  src/entities/place/api/get-place.ts
  src/entities/place/api/post-place-review.ts
  src/entities/place/api/queryKey.ts
  src/entities/place/api/update-place-review.ts
  src/entities/plan/api/delete-plan.ts
  src/entities/plan/api/get-plan.ts
  src/entities/plan/api/get-plans.ts
  src/entities/plan/api/queryKey.ts
  src/entities/plan/api/update-plan.ts
  src/features/comment-card/comment-card.tsx
  src/features/place-review/review-card.tsx
  src/views/detail-course/index.tsx
  src/views/list-comment/index.tsx
  src/widgets/review-form-layout/index.tsx
Labels: fix, refactor
