Repository team-joytas/wooco-fe, pull requests merged in 2025-05, with the labels that each got.

#259 [기능] 플랜을 코스로 공유하는 모달 추가 및 토스트 메세지용 컨텍스트 생성
  app/layout.tsx
  src/features/course-card/grid-card/grid-card.tsx
  src/features/course-card/list-card/list-card.tsx
  src/features/modal/index.ts
  src/features/modal/share-modal.tsx
  src/features/place-collapse/place-collapse.tsx
  src/features/place/form-review.tsx
  src/shared/lib/MessageProvider.tsx
  src/shared/lib/index.ts
  src/views/detail-place/index.tsx
  src/views/detail-plan/index.tsx
  src/widgets/course-plan-detail-layout/detail-layout.tsx
  src/widgets/course-plan-form-layout/index.tsx
Labels: feature

#262 [기능] 로그인 토큰 관리를 위한 AuthProvider, 토스트 컴포넌트를 위한 ToastProvider 추가
  app/layout.tsx
  app/oauth/[provider]/callback/page.tsx
  src/assets/icons/error.svg
  src/assets/images/(logo)/logo_long_light.svg
  src/entities/user/api/get-my-profile.ts
  src/entities/user/api/queryKey.ts
  src/entities/user/api/update-user-profile.ts
  src/features/course-card/action-bar/api/use-course-like.ts
  src/features/main/section-like-course.tsx
  src/features/modal/share-modal.tsx
  src/shared/provider/AppProviders.tsx
  src/shared/provider/AuthProvider.tsx
  src/shared/provider/ReactQueryProvider.tsx
  src/shared/provider/index.ts
  src/shared/ui/index.ts
  src/shared/ui/modal.tsx
  src/shared/ui/option-dropbox.tsx
  src/shared/ui/toast/Toast.tsx
  src/shared/ui/toast/ToastProvider.tsx
  src/shared/ui/toast/index.ts
  src/views/detail-course/index.tsx
  src/views/list-comment/index.tsx
  src/views/list-course/index.tsx
  src/views/list-plan/index.tsx
  src/views/update-user/index.tsx
  src/widgets/floating-write-btn/index.tsx
  src/widgets/header/course-plan-header.tsx
  src/widgets/header/main-header.tsx
  tailwind.config.ts
Labels: feature

#265 [디자인] 정렬 드롭다운 디자인 반영 및 위치 수정 (#248)
  src/features/select-sort/index.ts
  src/features/select-sort/option.tsx
  src/features/select-sort/options.ts
  src/features/select-sort/select-sort.tsx
  src/views/detail-user/index.tsx
  src/views/list-course/index.tsx
  src/views/list-like-course/index.tsx
Labels: style

#267 [기능] 일부 페이지에 Header 미표시
  src/widgets/header/main-header.tsx
Labels: design

#268 [기능 및 리팩토링] 플로팅 버튼의 오버레이 추가 및 폴더 구조 변경
  src/features/floating-write-btn/floating-write-btn.tsx
  src/features/floating-write-btn/index.ts
  src/features/floating-write-btn/menu-button.tsx
  src/features/index.ts
  src/views/detail-user/index.tsx
  src/views/list-course/index.tsx
  src/views/list-plan/index.tsx
  src/views/main-course/index.tsx
Labels: refactor, feature

#266 [기능] 코스 목록 페이지 제목 섹션 변경된 디자인 반영
  src/views/list-like-course/index.tsx
  src/views/main-course/index.tsx
Labels: design

#269 [수정-마이페이지] 탭 고정 위치 수정
  src/features/course-card/action-bar/ui/course-action-bar.tsx
  src/features/header-elements/title-with-tag-style.tsx
  src/features/user/user-profile-section.tsx
  src/widgets/header/action-header.tsx
  src/widgets/header/course-plan-header.tsx
Labels: fix, design

#271 [수정-코스 카드] 이미지 비정상일 경우 레이아웃이 깨지는 문제
  src/features/course-card/grid-card/grid-card.tsx
Labels: fix

#273 [기능] 유저 정보 수정 페이지의 프로필 이미지 영역 디자인 변경
  src/assets/icon/large/profile_empty.svg
  src/features/user/upload-profile-image.tsx
  src/shared/ui/profile-image.tsx
  src/views/update-user/index.tsx
  tailwind.config.ts
Labels: fix, design

#275 [기능] 드롭다운, 모달 기능 구현 (DeleteModal, CancelModal 추가)
  src/assets/icon/medium/link.svg
  src/assets/icon/medium/share_white.svg
  src/features/action-dropdown/action-dropdown.tsx
  src/features/action-dropdown/index.ts
  src/features/comment-card/comment-card.tsx
  src/features/index.ts
  src/features/modal/cancel-modal.tsx
  src/features/modal/delete-modal.tsx
  src/features/modal/index.ts
  src/features/modal/share-modal.tsx
  src/features/place-review/review-card.tsx
  src/shared/ui/index.ts
  src/shared/ui/kebab-menu.tsx
  src/shared/ui/modal.tsx
  src/shared/ui/option-dropbox.tsx
  src/views/detail-place/index.tsx
  src/views/list-place-review/index.tsx
  src/widgets/course-plan-detail-layout/detail-layout.tsx
  src/widgets/course-plan-detail-layout/skeleton-layout.tsx
  src/widgets/header/course-plan-header.tsx
Labels: feature

#277 [리팩토링] 안쓰는 코드 삭제 및 export용 barrel 파일 추가
  app/layout.tsx
  src/features/index.ts
  src/features/plan/index.ts
  src/features/plan/list-user-place.tsx
  src/views/detail-user/index.tsx
Labels: refactor

#279 [수정] 코스 상세 페이지에서 댓글 KebabMenu 아이콘 미표시
  src/features/comment-card/comment-card.tsx
  src/views/detail-course/index.tsx
  src/views/list-comment/index.tsx
Labels: fix

#280 [수정-코스,플랜 목록] 플로팅 버튼의 z-index 조정
  src/features/floating-write-btn/floating-write-btn.tsx
Labels: fix

#286 [기능] 장소 검색/추가 페이지 세부 디자인 변경
  src/views/search-place/index.tsx
Labels: design

#292 [수정-코스 목록] 지역 Cascader 스타일 수정
  src/shared/ui/region-cascader.tsx
Labels: feature, design

#291 [수정 및 기능] iOS 모바일에서 input, textarea 확대되는 문제 해결
  src/features/comment-card/comment-card.tsx
  src/features/course-form/elements/contents.tsx
  src/features/course-form/elements/title.tsx
  src/features/place/form-review.tsx
  src/views/list-comment/index.tsx
  src/views/onboard/index.tsx
  src/views/search-place/index.tsx
  src/views/update-user/index.tsx
Labels: fix, feature

#294 [긴급] 코스, 플랜 생성 오류 해결
  src/features/course-form/elements/contents.tsx
Labels: fix
