Repository team-joytas/wooco-fe, pull requests merged in 2025-02, with the labels that each got.

#91 [수정] 유저 코스 없을 시 ui 추가
  src/features/course/list-user-course.tsx
  src/views/detail-user/index.tsx
Labels: feature

#90 [수정] 댓글 삭제 api 연결
  src/entities/comment/api.ts
  src/entities/comment/query.ts
  src/entities/comment/type.ts
  src/features/comment/card-comment.tsx
  src/views/detail-comment/index.tsx
  src/views/detail-course/index.tsx
Labels: feature

#92 [수정] 유저 위시리스트 로직 수정 및 컴포넌트 분리
  app/users/[id]/wishlist/page.tsx
  src/entities/course/query.ts
  src/features/main/section-like-course.tsx
  src/shared/ui/NoLikedCourse.tsx
  src/shared/ui/RegionCascader.tsx
  src/shared/ui/SelectCategories.tsx
  src/views/list-course/index.tsx
  src/views/list-like-course/index.tsx
  src/views/main-course/index.tsx
  src/widgets/course-list-layout/index.tsx
Labels: fix, refactor

#94 [수정] 관심 지역 목록 관련 오류 수정 및 리팩토링
  src/entities/user/query.ts
  src/shared/store/regionStore.ts
  src/shared/ui/RegionCascader.tsx
  src/views/list-course/index.tsx
  src/views/main-course/index.tsx
Labels: fix, refactor

#95 [수정] 플랜의 카테고리 항목 삭제
  src/features/course/form-course.tsx
Labels: fix

#96 [수정] 카테고리 설정 기능 수정
  src/features/course/form-course.tsx
  src/shared/ui/SelectCategories.tsx
Labels: fix

#97 [수정] 플랜-코스로 공유 기능의 연동 정보 수정
  src/features/course/form-course.tsx
  src/widgets/course-plan-detail-layout/index.tsx
  src/widgets/course-plan-form-layout/index.tsx
Labels: fix

#110 [기능 및 수정] DatePicker max/min 제한, 임의 지역을 선택한 코스 목록에서 플로팅 버튼 미등장
  src/features/course/form-course.tsx
  src/views/list-course/index.tsx
  src/views/main-course/index.tsx
Labels: fix, feature

#127 [수정] 플랜-코스 edit 중 장소 순서 변경 로직 수정
  src/features/course/form-course.tsx
  src/shared/ui/KakaoMap.tsx
  src/widgets/course-plan-detail-layout/index.tsx
  src/widgets/course-plan-form-layout/index.tsx
  src/widgets/drag-place/index.tsx
Labels: fix

#133 hotfix: 빌드 에러 해결
  src/shared/ui/KakaoMap.tsx
Labels: fix

#129 [디자인] 인덱스 표시 이미지 스타일 수정
  src/shared/ui/ImageWithIndex.tsx
Labels: fix, style

#130 [기능] HelperText 컴포넌트 추가
  src/features/course/form-course.tsx
  src/shared/ui/HelperText.tsx
Labels: fix, style

#128 [기능 및 수정] 플랜 목록이 비어있는 경우, 안내 문구와 플로팅 버튼의 겹침 해결
  app/globals.css
  src/features/plan/blank-tooltip.tsx
  src/views/list-plan/index.tsx
  src/widgets/floating-write-btn/index.tsx
Labels: fix, feature, style

#134 [기능] Collapse 스타일 수정
  src/assets/images/(logo)/temp_empty.png
  src/shared/ui/PlaceCollapse.tsx
  src/widgets/course-plan-detail-layout/index.tsx
Labels: feature, style

#139 [빌드] 빌드 에러 해결
  src/widgets/floating-write-btn/index.tsx
Labels: fix

#140 [디자인] 폰트 설정 및 푸터 디자인 수정
  app/layout.tsx
  src/widgets/default-footer/index.tsx
Labels: fix, style

#142 [수정] 카카오맵 컴포넌트 추가
  src/entities/place/type.ts
  src/features/course/form-course.tsx
  src/shared/ui/KakaoMap.tsx
  src/widgets/course-plan-detail-layout/index.tsx
  tailwind.config.ts
Labels: fix, feature

#143 [기능] 장소 상세 페이지 구현
  app/places/[id]/page.tsx
  app/places/[id]/reviews/[review-id]/page.tsx
  app/places/[id]/reviews/new/page.tsx
  app/places/[id]/reviews/page.tsx
  src/assets/images/all_review_long.png
  src/assets/images/kakao_review_long.png
  src/entities/place/api.ts
  src/entities/place/query.ts
  src/entities/place/type.ts
  src/entities/user/type.ts
  src/features/place/card-review.tsx
  src/features/place/review-tag.tsx
  src/features/place/stats-review.tsx
  src/features/plan/card-user-place.tsx
  src/features/user/user-tab-button.tsx
  src/shared/ui/OptionDropbox.tsx
  src/shared/utils/date.ts
  src/views/detail-place/index.tsx
  src/widgets/default-footer/index.tsx
  src/widgets/default-header/index.tsx
  src/widgets/header/index.tsx
Labels: feature

#144 [기능] 장소 리뷰 목록 페이지 구현
  app/places/[id]/reviews/page.tsx
  src/entities/place/api.ts
  src/entities/place/query.ts
  src/features/place/card-review.tsx
  src/shared/ui/OptionDropbox.tsx
  src/views/detail-place/index.tsx
  src/views/list-place-review/index.tsx
  src/widgets/default-header/index.tsx
  src/widgets/header/index.tsx
Labels: feature

#148 [디자인 및 기능] 세부 디자인 및 이미지 커스텀 로더 추가
  src/features/main/section-announcement.tsx
  src/features/main/section-banner.tsx
  src/features/main/section-bottom.tsx
  src/features/main/section-like-course.tsx
  src/features/main/section-new-course.tsx
  src/features/plan/blank-tooltip.tsx
  src/shared/ui/ProfileImage.tsx
  src/views/detail-comment/index.tsx
  src/views/list-plan/index.tsx
  src/views/update-user/index.tsx
  src/widgets/course-plan-detail-layout/index.tsx
  src/widgets/default-header/index.tsx
  src/widgets/floating-write-btn/index.tsx
Labels: fix, feature, style

#149 [수정] 코스/플랜 생성 버튼 에러 해결
  src/widgets/floating-write-btn/index.tsx
Labels: fix

#153 [기능] 유저 드래그 액션 차단
  app/globals.css
Labels: fix, feature

#156 [수정] API 수정사항 적용
  src/entities/place/api.ts
  src/entities/place/type.ts
  src/entities/plan/type.ts
  src/features/main/section-like-course.tsx
  src/shared/ui/PlaceCollapse.tsx
  src/views/detail-place/index.tsx
  src/views/search-place/index.tsx
  src/widgets/course-plan-form-layout/index.tsx
Labels: fix

#157 [수정] 헤더 표시 위치 수정
  src/widgets/default-header/index.tsx
Labels: fix
