Repository team-joytas/wooco-fe, pull requests merged in 2025-03, with the labels that each got.

#169 [수정] 레이아웃 수정 및 장소 리뷰 작성/수정 기능 오류 해결
  app/places/[id]/reviews/[review-id]/page.tsx
  app/places/[id]/reviews/[review-id]/update/page.tsx
  app/places/[id]/reviews/new/page.tsx
  app/plans/[id]/update/page.tsx
  src/features/place/card-review.tsx
  src/features/place/stats-review.tsx
  src/views/detail-place/index.tsx
  src/views/update-plan/index.tsx
  src/views/update-review/index.tsx
  src/widgets/header/index.tsx
  src/widgets/review-form-layout/index.tsx
Labels: fix, style

#177 [기능] 알림 페이지 구현
  app/notifications/page.tsx
  public/bell.svg
  src/entities/notification/api.ts
  src/entities/notification/query.ts
  src/entities/notification/type.ts
  src/features/notification/card-notification.tsx
  src/views/list-notification/index.tsx
  src/widgets/default-footer/index.tsx
  src/widgets/default-header/index.tsx
  tailwind.config.ts
Labels: feature

#180 [수정] 마이페이지 코스 목록 정렬 오류 수정
  app/users/[id]/page.tsx
  src/entities/course/api.ts
  src/entities/course/query.ts
  src/features/main/section-new-course.tsx
  src/views/detail-user/index.tsx
  src/views/list-course/index.tsx
  src/views/list-like-course/index.tsx
  src/views/main-course/index.tsx
  src/views/search-course/index.tsx
  src/widgets/header/index.tsx
Labels: fix

#189 [리팩토링] next auth 마이그레이션
  app/api/auth/[...nextauth]/route.ts
  app/auth/callback/page.tsx
  app/layout.tsx
  app/oauth/kakao/callback/page.tsx
  package-lock.json
  package.json
  src/entities/login/api.ts
  src/features/main/section-like-course.tsx
  src/shared/lib/next-auth/options.ts
  src/shared/lib/next-auth/type.ts
  src/shared/provider/NextAuthSessionProvider.tsx
  src/views/list-plan/index.tsx
  src/views/login/index.tsx
  src/views/welcome/index.tsx
Labels: refactor

#191 [리팩토링] Shared 레이아웃의 api 디렉토리 FSD 구조 변경
  src/entities/auth/api/get-login-url.ts
  src/entities/auth/api/post-login.ts
  src/entities/comment/api/delete-comment.ts
  src/entities/comment/api/get-comments.ts
  src/entities/comment/api/post-comment.ts
  src/entities/comment/api/update-comment.ts
  src/entities/course/api/delete-course-like.ts
  src/entities/course/api/delete-course.ts
  src/entities/course/api/get-course.ts
  src/entities/course/api/get-courses.ts
  src/entities/course/api/post-course-like.ts
  src/entities/course/api/post-course.ts
  src/entities/course/api/update-course.ts
  src/entities/notification/api/get-notifications.ts
  src/entities/notification/api/read-notification.ts
  src/entities/place/api/delete-place-review.ts
  src/entities/place/api/get-place-review.ts
  src/entities/place/api/get-place-reviews.ts
  src/entities/place/api/get-place.ts
  src/entities/place/api/post-place-review.ts
  src/entities/place/api/post-place.ts
  src/entities/place/api/update-place-review.ts
  src/entities/plan/api/delete-plan.ts
  src/entities/plan/api/get-plan.ts
  src/entities/plan/api/get-plans.ts
  src/entities/plan/api/post-plan.ts
  src/entities/plan/api/update-plan.ts
  src/entities/user/api/delete-my-region-preferences.ts
  src/entities/user/api/get-my-like-courses.ts
  src/entities/user/api/get-my-profile.ts
  src/entities/user/api/get-my-regions-preferences.ts
  src/entities/user/api/get-user-courses.ts
  src/entities/user/api/get-user-profile.ts
  src/entities/user/api/post-my-regions-preferences.ts
  src/entities/user/api/update-user-profile.ts
  src/features/place/form-review.tsx
  src/features/user/upload-profile-image.tsx
  src/shared/api/axios/index.ts
  src/shared/api/axios/instance.ts
  src/shared/api/axios/signature.ts
  src/shared/api/image/get-image-upload-url.ts
  src/shared/api/image/index.ts
  src/shared/api/image/post-image.ts
  src/shared/api/index.ts
  src/shared/entities/api.ts
  src/widgets/default-footer/index.tsx
Labels: refactor

#192 [리팩토링] 코스, 플랜 목록의 카드 컴포넌트 디자인 수정 및 FSD 구조 변경
  src/entities/course/model/index.ts
  src/entities/course/model/mock.data.ts
  src/features/course-plan-card/index.ts
  src/features/course-plan-card/ui/course-grid-card.tsx
  src/features/course-plan-card/ui/course-list-card.tsx
  src/features/course-plan-card/ui/default-card.tsx
  src/features/course-plan-card/ui/index.ts
  src/features/course/card-course.tsx
  src/features/course/card-grid-course.tsx
  src/features/course/card-list-course.tsx
  src/features/course/grid-course.tsx
  src/features/course/list-user-course.tsx
  src/features/index.ts
  src/features/main/section-like-course.tsx
  src/features/main/section-new-course.tsx
  src/features/plan/card-plan.tsx
  src/shared/ui/SelectCategories.tsx
  src/views/list-course/index.tsx
  src/views/list-plan/index.tsx
  src/views/main-course/index.tsx
  src/views/search-course/index.tsx
  src/widgets/course-list-layout/index.tsx
  src/widgets/default-header/index.tsx
Labels: refactor, style

#194 [수정] 장소 Collapse 디자인 수정
  src/features/index.ts
  src/features/place-collapse/index.ts
  src/features/place-collapse/place-collapse.tsx
  src/widgets/course-plan-detail-layout/index.tsx
Labels: fix, style

#196 [기능] 나의 장소 리뷰 목록 조회 api 연결 및 기능 구현
  src/entities/place/api/get-place-reviews.ts
  src/entities/place/model/type.ts
  src/entities/user/api/endpoint.ts
  src/entities/user/api/get-my-place-reviews.ts
  src/entities/user/api/index.ts
  src/entities/user/api/queryKey.ts
  src/features/index.ts
  src/features/place-card/index.ts
  src/features/place-card/place-card.tsx
  src/features/place-review-stats/index.ts
  src/features/place-review-stats/review-stats.tsx
  src/features/place/review-tag.tsx
  src/features/plan/card-user-place.tsx
  src/features/plan/list-user-place.tsx
  src/features/review-tag/index.ts
  src/features/review-tag/review-tag.tsx
  src/views/detail-place/index.tsx
  src/views/detail-user/index.tsx
  src/widgets/review-comment-card/index.tsx
Labels: feature, high priority

#199 [수정-장소 리뷰 작성] 이미지 업로드 시도 시 페이지 나가짐 현상 수정
  src/features/place/form-review.tsx
Labels: fix

#200 [기능 및 디자인] 마이페이지 변경된 디자인 적용
  public/profile.png
  src/features/course-plan-card/ui/course-grid-card.tsx
  src/features/course-plan-card/ui/course-list-card.tsx
  src/features/user/user-profile-section.tsx
  src/shared/ui/ProfileImage.tsx
  src/views/detail-course/index.tsx
  src/views/list-plan/index.tsx
  src/widgets/default-footer/index.tsx
  src/widgets/review-comment-card/index.tsx
Labels: feature, style, high priority

#201 [수정-관심 목록] 알림 문구 명칭 변경
  src/shared/ui/NoLikedCourse.tsx
Labels: style

#205 [기능] 헤더 상단 고정
  src/widgets/default-header/index.tsx
Labels: fix, style

#206 [수정-장소 상세] 바로가기 버튼 이미지 화질 해결
  src/assets/images/all_review_icon.svg
  src/assets/images/kakao_review_icon.svg
  src/features/place-collapse/place-collapse.tsx
  src/views/detail-place/index.tsx
Labels: fix, style

#208 [기능] 장소 검색 결과 목록 디자인 적용
  src/features/place/form-review.tsx
  src/views/search-place/index.tsx
Labels: fix, style

#207 [수정-코스 상세] 장소 collapse 펼쳤을 경우 카카오맵 포커싱 변경
  src/features/place-collapse/place-collapse.tsx
  src/shared/ui/KakaoMap.tsx
  src/widgets/course-plan-detail-layout/index.tsx
Labels: fix

#210 feat: 인증관련 엔드 포인트 수정
  app/oauth/[provider]/callback/page.tsx
  src/entities/auth/api/get-login-url.ts
  src/entities/auth/api/post-login.ts
Labels: feature, high priority

#211 chore: 불필요 로그 삭제
  app/oauth/[provider]/callback/page.tsx
Labels: refactor
