Repository team-joytas/wooco-fe, pull requests merged in 2025-04, with the labels that each got.

#212 [수정] Hydration Error 해결을 위해 ProfileImage에 LegacyBehavior 옵션 추가
  src/shared/ui/ProfileImage.tsx
Labels: fix

#214 [기능] 장소 상세 리뷰 없는 화면 구성
  src/views/detail-place/index.tsx
  src/views/detail-place/section.tsx
Labels: refactor, feature

#215 [수정] global.css에 button, a의 기본 css 설정 추가
  app/globals.css
  src/features/course/form-course.tsx
  src/features/main/section-like-course.tsx
  src/features/notification/card-notification.tsx
  src/shared/ui/OptionDropbox.tsx
  src/views/detail-comment/index.tsx
  src/views/detail-course/index.tsx
  src/views/detail-place/index.tsx
  src/views/list-plan/index.tsx
  src/views/login/index.tsx
  src/views/update-user/index.tsx
  src/views/welcome/index.tsx
  src/widgets/course-plan-detail-layout/index.tsx
  src/widgets/default-header/index.tsx
  src/widgets/review-comment-card/index.tsx
  tsconfig.json
Labels: fix, build

#216 [리팩토링] 장소 상세, 유저 페이지의 탭 컴포넌트화 및 수정
  src/features/index.ts
  src/features/tabs/index.ts
  src/features/tabs/model/index.ts
  src/features/tabs/model/type.ts
  src/features/tabs/ui/index.ts
  src/features/tabs/ui/navigation-tab.tsx
  src/features/tabs/ui/scroll-tab.tsx
  src/features/user/user-tab-button.tsx
  src/shared/ui/index.ts
  src/shared/ui/tab-button.tsx
  src/views/detail-place/index.tsx
  src/views/detail-user/index.tsx
Labels: refactor, feature

#218 [수정] 장소 상세 페이지의 리뷰 길이 판단 조건문 수정
  src/views/detail-place/index.tsx
Labels: fix

#220 [기능] 유저 페이지용 유저 정보 조회 API 연결 및 코드 리팩토링
  src/entities/user/api/endpoint.ts
  src/entities/user/api/get-user-summary.ts
  src/entities/user/api/index.ts
  src/entities/user/model/type.ts
  src/features/user/user-profile-section.tsx
  src/views/detail-user/index.tsx
Labels: refactor, feature

#219 [디자인 및 기능] 코스 목록 아이템에 수정된 디자인 반영 및 플랜으로 추가하는 기능 추가
  src/features/course-action-bar/api/index.ts
  src/features/course-action-bar/api/use-course-like.ts
  src/features/course-action-bar/index.ts
  src/features/course-action-bar/ui/course-action-bar.tsx
  src/features/course-action-bar/ui/index.ts
  src/features/course-card/grid-card.tsx
  src/features/course-card/index.ts
  src/features/course-card/list-card.tsx
  src/features/course-plan-card/index.ts
  src/features/course-plan-card/ui/course-grid-card.tsx
  src/features/course-plan-card/ui/course-list-card.tsx
  src/features/course-plan-card/ui/index.ts
  src/features/course/list-user-course.tsx
  src/features/index.ts
  src/features/main/section-like-course.tsx
  src/features/main/section-new-course.tsx
  src/features/modal/course-modal.tsx
  src/shared/ui/modal.tsx
  src/views/list-plan/index.tsx
  src/views/main-course/index.tsx
  src/widgets/course-list-layout/index.tsx
  src/widgets/course-plan-card/course-plan-card.tsx
  src/widgets/course-plan-card/index.ts
  src/widgets/course-plan-detail-layout/index.tsx
  src/widgets/course-plan-form-layout/index.tsx
  src/widgets/index.ts
  tailwind.config.ts
Labels: feature, style

#223 [수정] queryKey 관련 빌드 에러 수정 및 코스 목록 조회 시 변경된 좋아요 반영
  src/entities/comment/api/delete-comment.ts
  src/entities/comment/api/update-comment.ts
  src/entities/course/api/delete-course.ts
  src/entities/course/api/get-courses.ts
  src/entities/course/api/post-course.ts
  src/entities/course/api/queryKey.ts
  src/entities/notification/api/read-notification.ts
  src/entities/place/api/delete-place-review.ts
  src/entities/place/api/post-place-review.ts
  src/entities/place/api/update-place-review.ts
  src/entities/user/api/delete-my-region-preferences.ts
  src/entities/user/api/post-my-regions-preferences.ts
  src/features/notification/card-notification.tsx
  src/widgets/course-plan-form-layout/index.tsx
  src/widgets/header/index.tsx
  src/widgets/review-comment-card/index.tsx
Labels: fix, build

#224 [수정 및 리팩토링] 헤더 수정 및 코드 디렉토리 구조 변경
  app/layout.tsx
  app/notices/1/page.tsx
  src/features/header-elements/header-base.tsx
  src/features/header-elements/index.ts
  src/features/header-elements/title-with-tag-style.tsx
  src/features/header-elements/view-type-toggle-button.tsx
  src/features/index.ts
  src/shared/ui/back-button.tsx
  src/shared/ui/index.ts
  src/views/detail-comment/index.tsx
  src/views/detail-place/index.tsx
  src/views/detail-user/index.tsx
  src/views/list-course/index.tsx
  src/views/list-like-course/index.tsx
  src/views/list-notification/index.tsx
  src/views/list-place-review/index.tsx
  src/views/search-place/index.tsx
  src/views/update-user/index.tsx
  src/widgets/course-plan-detail-layout/index.tsx
  src/widgets/course-plan-form-layout/index.tsx
  src/widgets/header/action-header.tsx
  src/widgets/header/course-plan-header.tsx
  src/widgets/header/index.ts
  src/widgets/header/index.tsx
  src/widgets/header/main-header.tsx
  src/widgets/index.ts
  src/widgets/review-form-layout/index.tsx
Labels: fix, refactor

#225 [수정] 유저 정보 조회 관련 오류 해결
  src/entities/user/api/get-user-summary.ts
  src/views/update-user/index.tsx
Labels: fix, refactor

#226 [리팩토링] Divider 컴포넌트 추가 및 적용
  src/features/course-form/course-form.tsx
  src/features/course-form/elements/divider.tsx
  src/features/course-form/elements/index.ts
  src/shared/ui/spacer.tsx
  src/views/update-user/index.tsx
  src/widgets/course-plan-detail-layout/index.tsx
Labels: refactor

#228 [기능] 스켈레톤 컴포넌트 추가 및 레이아웃 일부 구현
  src/features/course-card/grid-card/grid-card.tsx
  src/features/course-card/grid-card/index.ts
  src/features/course-card/grid-card/skeleton-grid-card.tsx
  src/features/course-card/list-card/index.ts
  src/features/course-card/list-card/list-card.tsx
  src/features/course-card/list-card/skeleton-list-card.tsx
  src/features/course-plan-card/index.ts
  src/features/course-plan-card/skeleton-card.tsx
  src/features/main/section-like-course.tsx
  src/features/main/section-new-course.tsx
  src/shared/ui/region-cascader.tsx
  src/shared/ui/skeleton.tsx
  src/views/detail-course/index.tsx
  src/views/detail-plan/index.tsx
  src/views/list-course/index.tsx
  src/views/list-plan/index.tsx
  src/views/main-course/index.tsx
  src/widgets/course-list-layout/index.tsx
  src/widgets/course-plan-detail-layout/detail-layout.tsx
  src/widgets/course-plan-detail-layout/index.ts
  src/widgets/course-plan-detail-layout/skeleton-layout.tsx
  src/widgets/header/course-plan-header.tsx
  src/widgets/index.ts
Labels: feature

#233 [기능] 알림 서비스 Firebase Cloud Messaging 연결
  firbase.ts
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/entities/auth/api/post-login.ts
  src/entities/notification/api/index.ts
  src/entities/notification/api/post-deviceToken.ts
  src/entities/notification/model/type.ts
  src/features/firebase/firebase-cloud-message.tsx
  src/features/firebase/index.ts
  src/features/index.ts
  src/features/notification/card-notification.tsx
  src/views/list-notification/index.tsx
Labels: fix, feature, high priority

#239 [수정] 알림 서비스 Firebase Cloud Messaging 연결(2)
  public/firebase-messaging-sw.js
  public/logo_gradation.svg
  src/features/firebase/firebase-cloud-message.tsx
Labels: fix, refactor

#242 [기능 및 수정] 장소 상세 페이지의 디자인 반영 및 기능 수정
  firbase.ts
  src/entities/place/api/get-place-reviews.ts
  src/features/header-elements/title-with-tag-style.tsx
  src/views/detail-comment/index.tsx
  src/views/detail-place/index.tsx
  src/views/list-place-review/index.tsx
  src/widgets/default-footer/index.tsx
  src/widgets/header/action-header.tsx
  src/widgets/review-comment-card/index.tsx
Labels: fix, feature, high priority

#243 [플랜 공유] 플랜을 코스로 변환하는 과정에서 미래 날짜 데이터가 그대로 넘어오는 현상 수정
  src/entities/course/api/get-course.ts
  src/entities/plan/api/get-plan.ts
  src/widgets/course-plan-detail-layout/detail-layout.tsx
  src/widgets/course-plan-form-layout/index.tsx
Labels: fix, high priority

#253 [기능] 장소 리뷰 이미지 페이지 구현
  src/assets/icons/left.svg
  src/assets/icons/right.svg
  src/features/place-review/image-view.tsx
  src/features/place-review/index.ts
  src/features/place-review/review-card.tsx
  src/views/detail-place/index.tsx
Labels: refactor, feature

#254 [기능] 댓글 수정 변경된 UI 구현
  src/features/comment-card/comment-card.tsx
  src/features/comment-card/index.ts
  src/features/index.ts
  src/views/detail-comment/index.tsx
  src/views/detail-course/index.tsx
  src/views/list-place-review/index.tsx
  src/widgets/review-comment-card/index.tsx
  tailwind.config.ts
Labels: feature, style, high priority

#255 [리팩토링] TitleWithTagStyle 컴포넌트 리팩토링
  src/features/header-elements/title-with-tag-style.tsx
  src/widgets/header/course-plan-header.tsx
Labels: refactor

#256 [수정/긴급] TitleWithTagStyle의 title 길이 연산자 수정
  src/features/header-elements/title-with-tag-style.tsx
Labels: fix, high priority

#257 [기능] 스켈레톤 레이아웃 구현
  src/features/course-card/grid-card/skeleton-grid-card.tsx
  src/features/course-card/list-card/skeleton-list-card.tsx
  src/features/course-plan-card/skeleton-card.tsx
  src/features/index.ts
  src/features/place-review/index.ts
  src/features/place-review/review-card.tsx
  src/features/place-review/skeleton/index.ts
  src/features/place-review/skeleton/skeleton-review-card.tsx
  src/features/place-review/skeleton/skeleton-review-stats.tsx
  src/features/place-review/skeleton/skeleton-start-view.tsx
  src/features/tabs/ui/index.ts
  src/features/tabs/ui/skeletons/index.ts
  src/features/tabs/ui/skeletons/skeleton-tab.tsx
  src/features/user/index.ts
  src/features/user/skeletons/index.ts
  src/features/user/skeletons/skeleton-user-profile-section.tsx
  src/shared/ui/index.ts
  src/shared/ui/skeletons/index.ts
  src/shared/ui/skeletons/skeleton-div.tsx
  src/shared/ui/skeletons/skeleton-tab-button.tsx
  src/views/detail-place/index.tsx
  src/views/detail-place/skeleton-layout.tsx
  src/views/detail-place/skeleton-section.tsx
  src/views/detail-user/index.tsx
  src/views/list-like-course/index.tsx
  src/views/list-place-review/index.tsx
  src/views/list-plan/index.tsx
  src/widgets/course-plan-detail-layout/skeleton-layout.tsx
Labels: feature

#258 [리팩토링/수정] User 관련 Features 폴더 구조 리팩토링 및 리뷰 평점 수정
  src/features/place-collapse/place-collapse.tsx
  src/features/user/index.ts
  src/features/user/upload-profile-image.tsx
  src/features/user/user-profile-section.tsx
  src/features/user/user-tag.tsx
  src/views/detail-user/index.tsx
  src/views/update-user/index.tsx
Labels: fix
